name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/icon-tw.png
    - assets/page-1/images/image-13.png
    - assets/page-1/images/basic-spaghetti.png
    - assets/page-1/images/basic-spaghetti-v7T.png
    - assets/page-1/images/sausage.png
    - assets/page-1/images/sausage-SiV.png
    - assets/page-1/images/m-b-bm.png
    - assets/page-1/images/profile-icon.png
    - assets/page-1/images/ellipse-8.png
    - assets/page-1/images/pepper-lunch.png
    - assets/page-1/images/spaghetti-creamy-marinara.png
    - assets/page-1/images/ellipse-17.png
    - assets/page-1/images/m-ba-ri-xng-khi-st-kem.png
    - assets/page-1/images/ellipse-14.png
    - assets/page-1/images/icon-tw-R2Z.png
    - assets/page-1/images/ellipse-12.png
    - assets/page-1/images/ellipse-14-Unm.png
    - assets/page-1/images/cart-icon.png
    - assets/page-1/images/sausage-PaH.png
    - assets/page-1/images/profile-icon-iVP.png
    - assets/page-1/images/profile-icon-m7P.png
    - assets/page-1/images/ellipse-14-Gfj.png
    - assets/page-1/images/m-b-bm-cqP.png
    - assets/page-1/images/spaghetti-creamy-marinara-ep1.png
    - assets/page-1/images/m-b-bm-wSH.png
    - assets/page-1/images/ellipse-9.png
    - assets/page-1/images/ellipse-8-a5o.png
    - assets/page-1/images/cart-icon-PhK.png
    - assets/page-1/images/ellipse-18.png
    - assets/page-1/images/ellipse-16.png
    - assets/page-1/images/ellipse-13.png
    - assets/page-1/images/ellipse-15.png
    - assets/page-1/images/ellipse-9-7Y5.png
    - assets/page-1/images/image-19.png
    - assets/page-1/images/image-19-4TK.png
    - assets/page-1/images/ellipse-13-M6q.png
    - assets/page-1/images/image-10.png
    - assets/page-1/images/ellipse-17-4X3.png
    - assets/page-1/images/ellipse-12-GsB.png
    - assets/page-1/images/image-13-vB3.png
    - assets/page-1/images/ellipse-13-2js.png
    - assets/page-1/images/ellipse-16-Q6D.png
    - assets/page-1/images/ellipse-15-Cos.png
    - assets/page-1/images/ellipse-18-MAy.png
    - assets/page-1/images/ellipse-16-D2h.png
    - assets/page-1/images/ellipse-18-NAV.png
    - assets/page-1/images/ellipse-15-Ld7.png
    - assets/page-1/images/spaghetti-creamy-marinara-hyT.png
    - assets/page-1/images/cart-icon-fpD.png
    - assets/page-1/images/cart-icon-UjK.png
    - assets/page-1/images/ellipse-17-FEH.png
    - assets/page-1/images/pepper-lunch-1z9.png
    - assets/page-1/images/image-10-PrH.png
    - assets/page-1/images/m-ba-ri-xng-khi-st-kem-e41.png
    - assets/page-1/images/spaghetti-creamy-marinara-7yB.png
    - assets/page-1/images/pepper-lunch-fGV.png
    - assets/page-1/images/ellipse-12-Xxm.png
    - assets/page-1/images/m-ba-ri-xng-khi-st-kem-Vgd.png
    - assets/page-1/images/basic-spaghetti-9of.png
    - assets/page-1/images/m-b-bm-f37.png
    - assets/page-1/images/ellipse-13-b1s.png
    - assets/page-1/images/spaghetti-creamy-marinara-ndP.png
    - assets/page-1/images/ellipse-14-C6m.png
    - assets/page-1/images/ellipse-14-2Ks.png
    - assets/page-1/images/ellipse-16-TmB.png
    - assets/page-1/images/image-19-yjw.png
    - assets/page-1/images/ellipse-13-gyf.png
    - assets/page-1/images/cart-icon-Zny.png
    - assets/page-1/images/ellipse-14-kgR.png
    - assets/page-1/images/profile-icon-vnV.png
    - assets/page-1/images/m-ba-ri-xng-khi-st-kem-bmB.png
    - assets/page-1/images/sausage-d3X.png
    - assets/page-1/images/sausage-jUM.png
    - assets/page-1/images/ellipse-15-xvm.png
    - assets/page-1/images/profile-icon-xrD.png
    - assets/page-1/images/pepper-lunch-8Nd.png
    - assets/page-1/images/ellipse-18-CSu.png
    - assets/page-1/images/ellipse-17-gB3.png
    - assets/page-1/images/ellipse-15-Rdj.png
    - assets/page-1/images/ellipse-13-zQy.png
    - assets/page-1/images/m-b-bm-UHF.png
    - assets/page-1/images/ellipse-17-cV7.png
    - assets/page-1/images/ellipse-12-BiZ.png
    - assets/page-1/images/ellipse-16-caD.png
    - assets/page-1/images/cart-icon-2Dw.png
    - assets/page-1/images/ellipse-18-17f.png
    - assets/page-1/images/ellipse-17-8k1.png
    - assets/page-1/images/spaghetti-creamy-marinara-XaR.png
    - assets/page-1/images/m-ba-ri-xng-khi-st-kem-Apy.png
    - assets/page-1/images/pepper-lunch-mVB.png
    - assets/page-1/images/ellipse-12-rKb.png
    - assets/page-1/images/ellipse-15-bSq.png
    - assets/page-1/images/m-b-bm-H45.png
    - assets/page-1/images/basic-spaghetti-s5s.png
    - assets/page-1/images/image-19-EjT.png
    - assets/page-1/images/profile-icon-ozq.png
    - assets/page-1/images/ellipse-18-Ccy.png
    - assets/page-1/images/ellipse-16-i5X.png
    - assets/page-1/images/m-ba-ri-xng-khi-st-kem-4TK.png
    - assets/page-1/images/ellipse-12-kqf.png
    - assets/page-1/images/cart-icon-1Zj.png
    - assets/page-1/images/basic-spaghetti-X6H.png
    - assets/page-1/images/basic-spaghetti-drZ.png
    - assets/page-1/images/image-19-SLh.png
    - assets/page-1/images/image-19-qQm.png
    - assets/page-1/images/pepper-lunch-JYy.png
    - assets/page-1/images/m-b-bm-U6m.png
    - assets/page-1/images/spaghetti-creamy-marinara-Q6m.png
    - assets/page-1/images/pepper-lunch-bub.png
    - assets/page-1/images/basic-spaghetti-boX.png
    - assets/page-1/images/sausage-KCD.png
    - assets/page-1/images/cart-icon-N4R.png
    - assets/page-1/images/ellipse-18-6R7.png
    - assets/page-1/images/m-ba-ri-xng-khi-st-kem-9Qd.png
    - assets/page-1/images/sausage-xgh.png
    - assets/page-1/images/m-ba-ri-xng-khi-st-kem-joo.png
    - assets/page-1/images/ellipse-14-pcZ.png
    - assets/page-1/images/ellipse-17-nad.png
    - assets/page-1/images/m-b-bm-J4h.png
    - assets/page-1/images/image-19-vZf.png
    - assets/page-1/images/pepper-lunch-sdj.png
    - assets/page-1/images/ellipse-15-yPP.png
    - assets/page-1/images/profile-icon-xGR.png
    - assets/page-1/images/ellipse-15-wVb.png
    - assets/page-1/images/ellipse-12-3ah.png
    - assets/page-1/images/ellipse-16-UKB.png
    - assets/page-1/images/ellipse-17-U1P.png
    - assets/page-1/images/basic-spaghetti-dds.png
    - assets/page-1/images/spaghetti-creamy-marinara-MV3.png
    - assets/page-1/images/ellipse-18-J3K.png
    - assets/page-1/images/ellipse-12-pSu.png
    - assets/page-1/images/ellipse-13-Tuj.png
    - assets/page-1/images/sausage-fKP.png
    - assets/page-1/images/profile-icon-UV7.png
    - assets/page-1/images/ellipse-14-z97.png
    - assets/page-1/images/ellipse-13-qrZ.png
    - assets/page-1/images/m-ba-ri-xng-khi-st-kem-ACZ.png
    - assets/page-1/images/pepper-lunch-PbX.png
    - assets/page-1/images/ellipse-16-Deh.png
    - assets/page-1/images/cart-icon-JKj.png
    - assets/page-1/images/profile-icon-58V.png
    - assets/page-1/images/image-23.png
    - assets/page-1/images/image-21.png
    - assets/page-1/images/m-b-bm-79B.png
    - assets/page-1/images/m-b-bm-mkM.png
    - assets/page-1/images/sausage-hn9.png
    - assets/page-1/images/image-19-w5K.png
    - assets/page-1/images/basic-spaghetti-Hbf.png
    - assets/page-1/images/spaghetti-creamy-marinara-xRP.png
    - assets/page-1/images/image-25.png
    - assets/page-1/images/cart-icon-QXT.png
    - assets/page-1/images/profile-icon-oDj.png
    - assets/page-1/images/image-22.png
    - assets/page-1/images/image-22-W73.png
    - assets/page-1/images/image-20.png
    - assets/page-1/images/image-26.png
    - assets/page-1/images/image-23-akH.png
    - assets/page-1/images/image-25-gMo.png
    - assets/page-1/images/image-26-hS1.png
    - assets/page-1/images/cart-icon-ZGM.png
    - assets/page-1/images/profile-icon-uZj.png
    - assets/page-1/images/image-21-XxV.png
    - assets/page-1/images/image-23-D9b.png
    - assets/page-1/images/image-21-buK.png
    - assets/page-1/images/image-26-Pzh.png
    - assets/page-1/images/profile-icon-zMw.png
    - assets/page-1/images/image-23-P9B.png
    - assets/page-1/images/cart-icon-bX7.png
    - assets/page-1/images/image-25-ALZ.png
    - assets/page-1/images/image-25-YWV.png
    - assets/page-1/images/image-25-g4Z.png
    - assets/page-1/images/image-26-2qf.png
    - assets/page-1/images/image-23-p6d.png
    - assets/page-1/images/cart-icon-vhP.png
    - assets/page-1/images/image-23-ch7.png
    - assets/page-1/images/image-22-dds.png
    - assets/page-1/images/profile-icon-nm7.png
    - assets/page-1/images/image-25-zjB.png
    - assets/page-1/images/image-22-fuT.png
    - assets/page-1/images/profile-icon-bY5.png
    - assets/page-1/images/image-22-cND.png
    - assets/page-1/images/image-26-yiH.png
    - assets/page-1/images/image-21-JdX.png
    - assets/page-1/images/image-21-Y3j.png
    - assets/page-1/images/image-28.png
    - assets/page-1/images/image-21-FtM.png
    - assets/page-1/images/image-26-aaV.png
    - assets/page-1/images/combo-1.png
    - assets/page-1/images/pepper-lunch-czm.png
    - assets/page-1/images/cart-icon-9ku.png
    - assets/page-1/images/cart-icon-NWd.png
    - assets/page-1/images/profile-icon-6SM.png
    - assets/page-1/images/pepper-lunch-zXb.png
    - assets/page-1/images/cart-icon-pu7.png
    - assets/page-1/images/pepper-lunch-iEu.png
    - assets/page-1/images/image-21-oay.png
    - assets/page-1/images/image-21-REH.png
    - assets/page-1/images/pepper-lunch-9VB.png
    - assets/page-1/images/profile-icon-4Em.png
    - assets/page-1/images/profile-icon-8Nm.png
    - assets/page-1/images/image-21-UX3.png
    - assets/page-1/images/cart-icon-wiq.png
    - assets/page-1/images/combo-1-wcm.png
    - assets/page-1/images/combo-1-Ay7.png
    - assets/page-1/images/image-22-mE9.png
    - assets/page-1/images/image-25-FY5.png
    - assets/page-1/images/image-22-4VX.png
    - assets/page-1/images/image-26-t7s.png
    - assets/page-1/images/image-23-QMf.png
    - assets/page-1/images/image-71.png
    - assets/page-1/images/vector-5.png
    - assets/page-1/images/vector-4.png
    - assets/page-1/images/image-21-GED.png
    - assets/page-1/images/vector-6.png
    - assets/page-1/images/vector-6-9wf.png
    - assets/page-1/images/vector-6-kTb.png
    - assets/page-1/images/vector-6-wAh.png
    - assets/page-1/images/vector-6-cvD.png
    - assets/page-1/images/vector-5-WMo.png
    - assets/page-1/images/vector-5-WLH.png
    - assets/page-1/images/vector-5-gsj.png
    - assets/page-1/images/vector-5-t41.png
    - assets/page-1/images/vector-5-v6M.png
    - assets/page-1/images/vector-6-RUM.png
    - assets/page-1/images/vector-6-dqK.png
    - assets/page-1/images/vector-5-SdF.png
    - assets/page-1/images/vector-6-YBb.png
    - assets/page-1/images/vector-5-RTX.png
    - assets/page-1/images/vector-5-CJ5.png
    - assets/page-1/images/vector-5-EQq.png
    - assets/page-1/images/vector-6-mff.png
    - assets/page-1/images/vector-4-oNy.png
    - assets/page-1/images/vector-6-YL1.png
    - assets/page-1/images/vector-5-3m3.png
    - assets/page-1/images/vector-5-MJq.png
    - assets/page-1/images/vector-5-agH.png
    - assets/page-1/images/vector-5-pj3.png
    - assets/page-1/images/vector-6-H3P.png
    - assets/page-1/images/vector-4-MWy.png
    - assets/page-1/images/vector-6-9e9.png
    - assets/page-1/images/vector-5-v2D.png
    - assets/page-1/images/vector-6-yuT.png
    - assets/page-1/images/vector-6-fmj.png
    - assets/page-1/images/vector-7.png
    - assets/page-1/images/vector-5-8Bb.png
    - assets/page-1/images/vector-4-DZj.png
    - assets/page-1/images/vector-6-h8m.png
    - assets/page-1/images/vector-6-LRP.png
    - assets/page-1/images/image-68.png
    - assets/page-1/images/vector-5-9cM.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
